name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://ehcalabres:$HF_TOKEN@huggingface.co/spaces/ehcalabres/EMOVoice main
